<?php
/**
 * ProductListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\ProductList
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Collection Service
 *
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\ProductList\Test\Api;

use \GeminiCommerce\ProductList\Configuration;
use \GeminiCommerce\ProductList\ApiException;
use \GeminiCommerce\ProductList\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductListApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\ProductList
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkUpdateProductListAssociations
     *
     * Bulk update collection associations position.
     *
     */
    public function testBulkUpdateProductListAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProductList
     *
     * Create Collection.
     *
     */
    public function testCreateProductList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProductListAssociation
     *
     * Create Collection/Product Association.
     *
     */
    public function testCreateProductListAssociation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProductList
     *
     * Delete Collection.
     *
     */
    public function testDeleteProductList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProductListAssociation
     *
     * Delete Collection/Product Association.
     *
     */
    public function testDeleteProductListAssociation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductListAssociationsByProductGrn
     *
     * Get Collection/Product Associations by Product GRN.
     *
     */
    public function testGetProductListAssociationsByProductGrn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductListByCode
     *
     * Get Collection by Code.
     *
     */
    public function testGetProductListByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductListById
     *
     * Get Collection by Id.
     *
     */
    public function testGetProductListById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductListByUrlKey
     *
     * Get Collection by Url Key.
     *
     */
    public function testGetProductListByUrlKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductListsCount
     *
     * Get Collection Product Count.
     *
     */
    public function testGetProductListsCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listProductListAssociations
     *
     * List Collection/Product Associations.
     *
     */
    public function testListProductListAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listProductLists
     *
     * List Collections.
     *
     */
    public function testListProductLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProductLists
     *
     * Search Collections.
     *
     */
    public function testSearchProductLists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProductListsByIds
     *
     * Search Collections by Ids.
     *
     */
    public function testSearchProductListsByIds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProductList
     *
     * Update Collection.
     *
     */
    public function testUpdateProductList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
